import fs from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import assert from 'node:assert/strict';

const WOWY_PAGE = 'src/routes/wowy/+page.svelte';
const WOWY_PAGE_SERVER = 'src/routes/wowy/+page.server.js';

async function read(file) {
    return fs.readFile(path.resolve(process.cwd(), file), 'utf8');
}

test('WOWY leaderboard loader defaults to all time and supports Current and URL-selected seasons', async () => {
    const contents = await read(WOWY_PAGE_SERVER);

    assert.match(contents, /getActiveWowyPlayers/);
    assert.match(contents, /getWowyAllTimePlayers/);
    assert.match(contents, /getWowyLeaderboardSeasons/);
    assert.match(contents, /getWowyPublication/);
    assert.match(contents, /getWowySeasonPlayers/);
    assert.match(contents, /load\(\{ url, setHeaders \}\)/);
    assert.match(contents, /Promise\.all\(\[\s*getWowyLeaderboardSeasons\(\),\s*getWowyPublication\(\)/s);
    assert.match(contents, /url\.searchParams\.get\('season'\)/);
    assert.match(contents, /seasons\.includes\(requestedSeason\)/);
    assert.match(contents, /url\.searchParams\.get\('view'\) === 'current'/);
    assert.match(contents, /requestedSeasonValue\.trim\(\) === 'current'/);
    assert.match(contents, /let selectedView = selectedSeason !== null/);
    assert.match(contents, /'all-time'/);
    assert.match(contents, /getWowyAllTimePlayers\(\)/);
    assert.match(contents, /getActiveWowyPlayers\(\)/);
    assert.match(contents, /getWowySeasonPlayers\(selectedSeason\)/);
    assert.match(contents, /let isActivationFallback = false;/);
    assert.match(contents, /if \(players\.length === 0\)/);
    assert.match(contents, /selectedView = 'current';/);
    assert.match(contents, /isActivationFallback = true;/);
    assert.match(contents, /if \(isActivationFallback\) \{[\s\S]*'cache-control': 'no-store'/);
    assert.match(contents, /if \(isActivationFallback\) \{[\s\S]*'cdn-cache-control': 'no-store'/);
    assert.match(contents, /if \(isActivationFallback\) \{[\s\S]*'vercel-cdn-cache-control': 'no-store'/);
    assert.match(contents, /\} else \{\s*setEdgeCache\(setHeaders, \{/);
    assert.match(contents, /return \{ players, publication, seasons, selectedSeason, selectedView \}/);
    assert.match(contents, /setEdgeCache\(/);
    assert.match(contents, /edgeSMaxAge:\s*300/);
    assert.match(contents, /swr:\s*3600/);
});

test('WOWY leaderboard defaults to the all-time top 100 and preserves Current and season semantics', async () => {
    const contents = await read(WOWY_PAGE);

    assert.match(contents, /import \{ goto \} from '\$app\/navigation';/);
    assert.match(contents, /formatSeasonEndYearLabel/);
    assert.match(contents, /data\.selectedView === 'all-time'/);
    assert.match(contents, /const hasAllTimeRanks/);
    assert.match(contents, /return hasAllTimeRanks \? 'all-time' : 'current';/);
    assert.match(contents, /const isAllTimeView/);
    assert.match(contents, /The 100 highest unweighted WOWY RAPM player-seasons of all time/);
    assert.match(contents, /The 100 highest single-season WOWY RAPM averages/);
    assert.match(contents, /All-time top 100 seasons/);
    assert.match(contents, /raw, simple, unweighted average across published WOWY games/);
    assert.match(contents, /no sample or exposure cutoff/);
    assert.match(contents, /current season can move as new games are published/);
    assert.match(contents, /<option value="all-time">All time<\/option>/);
    assert.match(contents, /Latest observed/);
    assert.match(contents, /isCurrentView[\s\S]*Latest observed WOWY RAPM ratings for current active NBA players/);
    assert.match(contents, /Unweighted season-average WOWY RAPM ratings for NBA players/);
    assert.match(contents, /does not use DARKO projection rows/);
    assert.match(contents, /Current active players/);
    assert.match(contents, /<option value="current">Current<\/option>/);
    assert.match(contents, /id="wowy-season-filter"/);
    assert.match(contents, /data\.selectedSeason === null/);
    assert.match(contents, /selection === 'all-time'/);
    assert.match(contents, /\?view=current/);
    assert.match(contents, /goto\(`\/wowy\$\{suffix\}`, \{[\s\S]*keepFocus: true,[\s\S]*invalidateAll: selection === 'all-time'[\s\S]*\}\);/);
    assert.match(contents, /historicalSnapshotContext/);
    assert.match(contents, /getWowyHistoricalSnapshotContext\(players, isHistoricalSeason\)/);
    assert.match(contents, /isWowySeasonAverageContext\(historicalSnapshotContext\)/);
    assert.match(contents, /isSeasonAverageHistory/);
    assert.match(contents, /Unweighted season-average RAPM/);
    assert.match(contents, /Each row is a simple, unweighted average of that player’s observed game-level WOWY values/);
    assert.match(contents, /Unweighted season average/);
    assert.match(contents, /Opening-game snapshot RAPM/);
    assert.match(contents, /Each row is a player who appeared in their team’s first game/);
    assert.match(contents, /Opening-game snapshot of players who appeared in their teams' first games/);
    assert.match(contents, /snapshot_context/);
    assert.match(contents, /team_code/);
    assert.match(contents, /team_codes/);
    assert.match(contents, /team_names/);
    assert.match(contents, /isHistoricalSeasonSummary/);
    assert.match(contents, /teamFilterValues/);
    assert.match(contents, /teamOptionEntries/);
    assert.match(contents, /if \(isHistoricalSeasonSummary\(player\)\)/);
    assert.match(contents, /wowy_rapm/);
    assert.match(contents, /wowy_orapm/);
    assert.match(contents, /wowy_drapm/);
    assert.match(contents, /exposure/);
    assert.match(contents, /career_game_num/);
    assert.match(contents, /season_games/);
    assert.match(contents, /leaderboard_rank/);
    assert.match(contents, /allTimeRank\(player, fallbackRank\)/);
    assert.match(contents, /function playerRowKey\(player\)/);
    assert.match(contents, /\{#each visiblePlayers as player, index \(playerRowKey\(player\)\)\}/);
    assert.match(contents, /formatPlayerSeason\(player\)/);
    assert.match(contents, /allTimeTableColumns/);
    assert.match(contents, /label: 'Season'/);
    assert.match(contents, /last_date/);
    assert.match(contents, /Avg WOWY RAPM/);
    assert.match(contents, /Last game/);
    assert.match(contents, /openingGameTableColumns/);
    assert.match(contents, /seasonAverageTableColumns/);
    assert.match(contents, /publication\.data_through/);
    assert.match(contents, /\/trajectories\?ids=\$\{encodeURIComponent\(player\.nba_id\)\}&metric=wowy_rapm/);
    assert.doesNotMatch(contents, /Final observed/i);
    assert.doesNotMatch(contents, /opening roster/i);
    assert.doesNotMatch(contents, /before that team’s opening game/i);
    assert.doesNotMatch(contents, /Observed leaders|leaderCards|buildLeaderCard|wowy-leader-/);
});

test('WOWY leaderboard supports sorting, filtering, complete CSV export, and mobile table access', async () => {
    const contents = await read(WOWY_PAGE);
    const desktopColumnsStart = contents.indexOf('@media (hover: hover) and (pointer: fine) and (max-width: 980px)');
    const touchStart = contents.indexOf('/* Touch/mobile scroll mode */');
    const touchEnd = contents.indexOf('/* End touch/mobile scroll mode */');

    assert.match(contents, /getNextSortState/);
    assert.match(contents, /getSortedRows/);
    assert.match(contents, /aria-sort=\{sortColumn === column\.key/);
    assert.match(contents, /const seasonSortColumns = new Set/);
    assert.match(contents, /const allTimeSortColumns = new Set\(\[\.\.\.seasonSortColumns, 'season'\]\)/);
    assert.match(contents, /const currentSortColumns = new Set/);
    assert.match(contents, /const supportedSortColumns = nextView === 'all-time'/);
    assert.match(contents, /if \(!supportedSortColumns\.has\(sortColumn\)\)/);
    assert.match(contents, /sortColumn = 'wowy_rapm';/);
    assert.match(contents, /sortDirection = 'desc';/);
    assert.match(contents, /setTeamFilter/);
    assert.match(contents, /const positionOptions = \[/);
    assert.match(contents, /\{ value: 'G', label: 'Guards' \}/);
    assert.match(contents, /\{ value: 'F', label: 'Forwards' \}/);
    assert.match(contents, /\{ value: 'C', label: 'Centers' \}/);
    assert.match(contents, /let positionFilter = \$state\('all'\);/);
    assert.match(contents, /const activePositionFilter = \$derived/);
    assert.match(contents, /function playerFilterPosition\(player\)/);
    assert.match(contents, /player\?\.filter_position \?\? player\?\.position/);
    assert.match(contents, /function playerMatchesPosition\(player, positionGroup\)/);
    assert.match(contents, /split\('-'\)\.includes\(positionGroup\)/);
    assert.match(contents, /setPositionFilter/);
    assert.match(contents, /id="wowy-position-filter"/);
    assert.match(contents, /<option value="all">All positions<\/option>/);
    assert.match(contents, /let minHeight = \$state\(''\);/);
    assert.match(contents, /let maxHeight = \$state\(''\);/);
    assert.match(contents, /const heightOptions = \$derived\.by/);
    assert.match(contents, /function playerHeightInches\(player\)/);
    assert.match(contents, /player\?\.height_inches \?\? player\?\.height/);
    assert.match(contents, /height !== null && height > 0/);
    assert.match(contents, /function matchesHeightRange\(player, minimum, maximum\)/);
    assert.match(contents, /if \(minimum === null && maximum === null\) return true;/);
    assert.match(contents, /if \(height === null\) return false;/);
    assert.match(contents, /function formatHeightLabel\(value\)/);
    assert.match(contents, /function setHeightFilter\(bound, value\)/);
    assert.match(contents, /function clearHeightFilters\(\)/);
    assert.match(contents, /<details class="wowy-advanced-filters">/);
    assert.match(contents, /<summary>[\s\S]*Advanced filters/);
    assert.match(contents, /id="wowy-min-height-filter"/);
    assert.match(contents, /id="wowy-max-height-filter"/);
    assert.match(contents, /<option value="">No minimum<\/option>/);
    assert.match(contents, /<option value="">No maximum<\/option>/);
    assert.match(contents, /Players without a recorded height are excluded only when a bound is set/);
    assert.match(contents, /positionFilter = 'all';[\s\S]*minHeight = '';[\s\S]*maxHeight = '';/);
    assert.match(contents, /setSearchQuery/);
    assert.match(contents, /sortedPlayers\.map\(\(player, index\) => \(\{/);
    assert.match(contents, /rank: isAllTimeView \? allTimeRank\(player, index \+ 1\) : index \+ 1/);
    assert.match(contents, /wowyAllTimeLeaderboardCsvColumns/);
    assert.match(contents, /wowyLeaderboardCsvColumns/);
    assert.match(contents, /wowyHistoricalLeaderboardCsvColumns/);
    assert.match(contents, /wowyOpeningGameLeaderboardCsvColumns/);
    assert.match(contents, /isAllTimeView[\s\S]*wowyAllTimeLeaderboardCsvColumns[\s\S]*isCurrentView[\s\S]*wowyLeaderboardCsvColumns[\s\S]*isSeasonAverageHistory[\s\S]*wowyHistoricalLeaderboardCsvColumns[\s\S]*wowyOpeningGameLeaderboardCsvColumns/);
    assert.match(contents, /isSeasonAverageHistory \? 'season-average' : 'opening-game'/);
    assert.match(contents, /class:wowy-table--all-time=\{isAllTimeView\}/);
    assert.ok(desktopColumnsStart >= 0 && touchStart > desktopColumnsStart, 'page should define desktop column priorities');
    assert.ok(touchStart >= 0 && touchEnd > touchStart, 'page should define a touch-table mode');

    const desktopColumnsBlock = contents.slice(desktopColumnsStart, touchStart);
    assert.match(desktopColumnsBlock, /\.wowy-table:not\(\.wowy-table--all-time\) th:nth-child\(7\)/);
    assert.match(desktopColumnsBlock, /\.wowy-table:not\(\.wowy-table--all-time\) th:nth-child\(8\)/);
    assert.match(desktopColumnsBlock, /\.wowy-table--all-time th:nth-child\(8\)/);
    assert.match(desktopColumnsBlock, /\.wowy-table--all-time th:nth-child\(9\)/);
    assert.doesNotMatch(desktopColumnsBlock, /\.wowy-table--all-time th:nth-child\(7\)/);

    const touchBlock = contents.slice(touchStart, touchEnd);
    assert.match(touchBlock, /hover:\s*none/);
    assert.match(touchBlock, /pointer:\s*coarse/);
    assert.match(touchBlock, /any-hover:\s*none/);
    assert.match(touchBlock, /any-pointer:\s*coarse/);
    assert.match(touchBlock, /max-width:\s*1024px/);
    assert.match(touchBlock, /\.wowy-table-shell\s*\{[\s\S]*overflow-x:\s*auto;/);
    assert.match(touchBlock, /\.wowy-table\s*\{[\s\S]*width:\s*max-content;[\s\S]*min-width:\s*900px;/);
    assert.match(touchBlock, /\.wowy-table th\s*\{[\s\S]*position:\s*static;/);
    assert.match(contents, /\.wowy-table th\s*\{[\s\S]*position:\s*sticky;[\s\S]*top:\s*var\(--nav-sticky-offset\);/);
    assert.match(contents, /\.wowy-table-shell\s*\{[\s\S]*overflow:\s*visible;/);
    assert.match(contents, /@media \(max-width: 840px\)\s*\{[\s\S]*?\.wowy-table-shell\s*\{[\s\S]*?overflow-x:\s*auto;/);
    assert.match(contents, /@media \(max-width: 840px\)\s*\{[\s\S]*?\.wowy-table th\s*\{[\s\S]*?position:\s*static;/);
});
